### ISSUE TITLE
你好我运行react-native run-ios 报错

### ISSUE THREAD

**Issue by JserJser** [CoderLawrence/TodayNews#1]
Port 8081 already in use, packager is either not running or not running correctly

Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **

The following build commands failed:

	PhaseScriptExecution Start\ Packager /Users//523box/TodayNewsReactNative/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/TodayNews.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/TodayNews.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by CoderLawrence** [comment]
我抽时间维护一下
